# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vfox < Formula
  desc "A cross-platform SDK version manager with a simple cli."
  homepage "https://github.com/version-fox/vfox"
  version "0.9.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/version-fox/vfox/releases/download/v0.9.1/vfox_0.9.1_macos_x86_64.tar.gz"
      sha256 "f6689fc7a061ebc9cc1096718f8c2b3808b1288be3d2f958c23ec14e29f80f95"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/version-fox/vfox/releases/download/v0.9.1/vfox_0.9.1_macos_aarch64.tar.gz"
      sha256 "0987954327b524216310c7e1fe586f29a98713919e57452eeef6a149496034af"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v0.9.1/vfox_0.9.1_linux_x86_64.tar.gz"
      sha256 "79954bf5ee78de2da4a060b8ecc1309124b7bdfa7e849f61302ba2c49e13277a"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v0.9.1/vfox_0.9.1_linux_armv7.tar.gz"
      sha256 "feec4f72769076d3c18ebcbf766226f9262751d1b66dc71cb3dad4fa50c718fe"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v0.9.1/vfox_0.9.1_linux_aarch64.tar.gz"
      sha256 "ec9b511525380c5c64b2027d462bc7d248a5ea93736682524f7a35f256565ffb"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  test do
    system "#{bin}/vfox version"
  end
end
