# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vfox < Formula
  desc "A cross-platform SDK version manager with a simple cli."
  homepage "https://github.com/version-fox/vfox"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.0/vfox_1.0.0_macos_x86_64.tar.gz"
      sha256 "8dfc3f9bffa6128e3f3ca4497ac08963d31afa4adbd38333f485f6a3d0aeb699"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.0/vfox_1.0.0_macos_aarch64.tar.gz"
      sha256 "81cca143c5ff6e408fc857a31c89b27d6ff5d3a4c7489e24bd1e0a67adc5ffdc"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.0/vfox_1.0.0_linux_x86_64.tar.gz"
      sha256 "097544aa238b005736ac49e60f0cb29400bfb5145a8fe0f20bc45aae5aadd23d"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.0/vfox_1.0.0_linux_armv7.tar.gz"
      sha256 "89dfe776d89ee17235a1a21d7c3a0858c2ee7caec80d66d1cb3d2640ca46183f"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.0/vfox_1.0.0_linux_aarch64.tar.gz"
      sha256 "02278cf44f72595e7b1249485e685651e2aa117c9329863f7861e2ff29f754a9"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  test do
    system "#{bin}/vfox version"
  end
end
