# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vfox < Formula
  desc "A cross-platform SDK version manager with a simple cli."
  homepage "https://github.com/version-fox/vfox"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.1/vfox_1.0.1_macos_x86_64.tar.gz"
      sha256 "4970162a422f8260d5841fe4e190b0fab3f964ea4d0afa18e80cb2234b094139"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.1/vfox_1.0.1_macos_aarch64.tar.gz"
      sha256 "f083946ef5202f36c408ad85e95648249c4d039a6d5be3328212deb13a94de66"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.1/vfox_1.0.1_linux_x86_64.tar.gz"
      sha256 "4506e49169c0d272fdd41117b2f1a671753d7f6464b82683bcb421a64ebac534"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.1/vfox_1.0.1_linux_armv7.tar.gz"
      sha256 "3796d6b710b8d9defe1c3c8cf295b8775019e598ddc4e4e2dab28aa31a50531a"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v1.0.1/vfox_1.0.1_linux_aarch64.tar.gz"
      sha256 "b4b8d12e6cd8a0825808a8e4a95f55d22c9b0c4301b19f9cbe8d742253c98fc6"
      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  test do
    system "#{bin}/vfox version"
  end
end
