# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vfox < Formula
  desc "A cross-platform SDK version manager with a simple cli."
  homepage "https://github.com/version-fox/vfox"
  version "0.6.10"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/version-fox/vfox/releases/download/v0.6.10/vfox_0.6.10_macos_x86_64.tar.gz"
      sha256 "4a3b83f42a37af274b872fcb90798d790c0443bc2030323b5017862a2f094b78"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    on_arm do
      url "https://github.com/version-fox/vfox/releases/download/v0.6.10/vfox_0.6.10_macos_aarch64.tar.gz"
      sha256 "cefd9e22e78336ebac6afdffd8cbfcb503ca1868aad3cb811f2bc2aca8fcfc6b"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/version-fox/vfox/releases/download/v0.6.10/vfox_0.6.10_linux_x86_64.tar.gz"
        sha256 "f8520019234378eb26ff57619ae8d25c3db88048b4b1f3fbf27cce026cb887cb"

        def install
          bin.install "vfox"
          bash_completion.install "completions/bash_autocomplete" => "vfox"
          zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/version-fox/vfox/releases/download/v0.6.10/vfox_0.6.10_linux_armv7.tar.gz"
        sha256 "af4f2f3139aaddf5222f292b38f9c754dd0950e90edce27b4d6554790bded897"

        def install
          bin.install "vfox"
          bash_completion.install "completions/bash_autocomplete" => "vfox"
          zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/version-fox/vfox/releases/download/v0.6.10/vfox_0.6.10_linux_aarch64.tar.gz"
        sha256 "df32b2e250949cecf99382ad6020207630b1cabbecf0208e43c0e6f4b4b273d7"

        def install
          bin.install "vfox"
          bash_completion.install "completions/bash_autocomplete" => "vfox"
          zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
        end
      end
    end
  end

  test do
    system "#{bin}/vfox version"
  end
end
