# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vfox < Formula
  desc "A cross-platform SDK version manager with a simple cli."
  homepage "https://github.com/version-fox/vfox"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/version-fox/vfox/releases/download/v0.3.1/vfox_0.3.1_macos_aarch64.tar.gz"
      sha256 "1ef896ba0a5fb94aee210fed56d4e97d4f446ace4179235bc5825a12271babff"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/version-fox/vfox/releases/download/v0.3.1/vfox_0.3.1_macos_x86_64.tar.gz"
      sha256 "9d9628a0d5a7870a26c0990c904c9eedd860e2a2ad6aed3079b5af178e6daea9"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v0.3.1/vfox_0.3.1_linux_armv7.tar.gz"
      sha256 "62c62d071fcbb3e7782df58759810e5573e657ceb125d88614fa90403cbb7713"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/version-fox/vfox/releases/download/v0.3.1/vfox_0.3.1_linux_x86_64.tar.gz"
      sha256 "06ae214ae126c858b4d14e36fa01c8541cb41c42430f818f44a4d90d3acd71b4"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/version-fox/vfox/releases/download/v0.3.1/vfox_0.3.1_linux_aarch64.tar.gz"
      sha256 "c56da359705b3ecfd243b79efb5ad1263758e4829c9b726968388e174feecad0"

      def install
        bin.install "vfox"
        bash_completion.install "completions/bash_autocomplete" => "vfox"
        zsh_completion.install "completions/zsh_autocomplete" => "_vfox"
      end
    end
  end

  test do
    system "#{bin}/vfox version"
  end
end
