# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vfox < Formula
  desc "A cross-platform SDK version manager with a simple cli."
  homepage "https://github.com/aooohan/version-fox"
  version "0.0.1"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aooohan/version-fox/releases/download/v0.0.1/version-fox_Darwin_x86_64.tar.gz"
      sha256 "65df5de2f3792866dccaed3731cfdd0570abb2d6ad10290e0bcebda1d7143aa8"

      def install
        bin.install "vfox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aooohan/version-fox/releases/download/v0.0.1/version-fox_Darwin_arm64.tar.gz"
      sha256 "1bc92b5d8758405ec9e6222ee3e8a7bf410551c51f90806544efe513be3b2b0e"

      def install
        bin.install "vfox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aooohan/version-fox/releases/download/v0.0.1/version-fox_Linux_x86_64.tar.gz"
      sha256 "7c6e8e38717d3332a6a79a1f993e95ef2f93495338df99ad7ff0183e11d8bc66"

      def install
        bin.install "vfox"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aooohan/version-fox/releases/download/v0.0.1/version-fox_Linux_armv7.tar.gz"
      sha256 "57bf5387284a8fc142aba2e1e6b50509691b7c661607227f73cebe726039606a"

      def install
        bin.install "vfox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aooohan/version-fox/releases/download/v0.0.1/version-fox_Linux_arm64.tar.gz"
      sha256 "653f58dffc8591bd2030167a5048f4da69f0caae58d246248694a4f64e8d1596"

      def install
        bin.install "vfox"
      end
    end
  end

  test do
    system "#{bin}/vfox version"
  end
end
